### ISSUE TITLE
App crashes on Android 11 - SDK 30 (Invalid token LIMIT in getCollectionThumbnail)

### ISSUE THREAD

**Issue by AdrianSima** [aloisdeniel/media_gallery#28]
After settings `compiledSdkVersion` to 30 the app crashes every time I try to get collections or medias.

```E/AndroidRuntime( 6991): java.lang.RuntimeException: An error occurred while executing doInBackground()
E/AndroidRuntime( 6991): 	at android.os.AsyncTask$4.done(AsyncTask.java:415)
E/AndroidRuntime( 6991): 	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
E/AndroidRuntime( 6991): 	at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
E/AndroidRuntime( 6991): 	at java.util.concurrent.FutureTask.run(FutureTask.java:271)
E/AndroidRuntime( 6991): 	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:305)
E/AndroidRuntime( 6991): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
E/AndroidRuntime( 6991): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
E/AndroidRuntime( 6991): 	at java.lang.Thread.run(Thread.java:923)
E/AndroidRuntime( 6991): Caused by: java.lang.IllegalArgumentException: Invalid token LIMIT
E/AndroidRuntime( 6991): 	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:172)
E/AndroidRuntime( 6991): 	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:142)
E/AndroidRuntime( 6991): 	at android.content.ContentProviderProxy.query(ContentProviderNative.java:472)
E/AndroidRuntime( 6991): 	at android.content.ContentResolver.query(ContentResolver.java:1183)
E/AndroidRuntime( 6991): 	at android.content.ContentResolver.query(ContentResolver.java:1115)
E/AndroidRuntime( 6991): 	at android.content.ContentResolver.query(ContentResolver.java:1071)
E/AndroidRuntime( 6991): 	at com.example.media_gallery.MediaGalleryPlugin.getCollectionThumbnail(MediaGalleryPlugin.kt:427)
E/AndroidRuntime( 6991): 	at com.example.media_gallery.MediaGalleryPlugin.access$getCollectionThumbnail(MediaGalleryPlugin.kt:20)
E/AndroidRuntime( 6991): 	at com.example.media_gallery.MediaGalleryPlugin$onMethodCall$7.invoke(MediaGalleryPlugin.kt:92)
E/AndroidRuntime( 6991): 	at com.example.media_gallery.MediaGalleryPlugin$onMethodCall$7.invoke(MediaGalleryPlugin.kt:20)
E/AndroidRuntime( 6991): 	at com.example.media_gallery.doAsync.doInBackground(MediaGalleryPlugin.kt:538)
E/AndroidRuntime( 6991): 	at com.example.media_gallery.doAsync.doInBackground(MediaGalleryPlugin.kt:532)
E/AndroidRuntime( 6991): 	at android.os.AsyncTask$3.call(AsyncTask.java:394)
E/AndroidRuntime( 6991): 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
E/AndroidRuntime( 6991): 	... 4 more
Lost connection to device.
```

The error seems to be in the `getCollectionThumbnail()` function with: "Invalid token LIMIT".

Tested this on *Android Emulator with Pixel 4XL API 30* and **media_gallery: 0.1.5**.

**Comment by AdrianSima** [comment]
It works fine now after using this fork by @miyura https://github.com/Geostry/media_gallery
by changing this in pubspec.yaml:
```
dependencies:
    media_gallery:
        git:
          url: git://github.com/Geostry/media_gallery.git
```

**Comment by Ahmadre** [comment]
@aloisdeniel can we merge the fixes?

**Comment by benwinding** [comment]
Thanks @AdrianSima ! 

The only thing I would add, is that it's much safer to use the exact commit on the git repo, as the current master branch is broken. I use the following code:

``` yaml
  media_gallery:
    # Fixes issue: https://github.com/aloisdeniel/media_gallery/issues/28
    git:
      url: git://github.com/Geostry/media_gallery
      ref: f5b30c7298f01dcc1589b6ac450888010c0da9f3
```

That way future updates, to these forks, won't break the app

**Comment by rikai-trongpq** [comment]
Any update?

**Comment by rikai-trongpq** [comment]
> Thanks @AdrianSima !
> 
> The only thing I would add, is that it's much safer to use the exact commit on the git repo, as the current master branch is broken. I use the following code:
> 
> ```yaml
>   media_gallery:
>     # Fixes issue: https://github.com/aloisdeniel/media_gallery/issues/28
>     git:
>       url: git://github.com/Geostry/media_gallery
>       ref: f5b30c7298f01dcc1589b6ac450888010c0da9f3
> ```
> 
> That way future updates, to these forks, won't break the app

It's still crashed
```
aunching lib\main.dart on sdk gphone x86 in debug mode...
Running Gradle task 'assembleProductionDebug'...
/C:/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_datetime_picker-1.5.1/lib/flutter_datetime_picker.dart:311:32: Warning: Operand of null-aware operation '??' has type 'Color' which excludes null.
 - 'Color' is from 'dart:ui'.
                  color: theme.backgroundColor ?? Colors.white,
                               ^
e: C:\flutter\.pub-cache\git\media_gallery-fa79ba479b4254b62f5cad98cf77e12fd2b41bc8\android\src\main\kotlin\com\example\media_gallery\MediaGalleryPlugin.kt: (22, 7): Redeclaration: MediaGalleryPlugin
e: C:\flutter\.pub-cache\git\media_gallery-fa79ba479b4254b62f5cad98cf77e12fd2b41bc8\android\src\main\kotlin\com\example\media_gallery\MediaGalleryPlugin.kt: (609, 7): Redeclaration: doAsync
e: C:\flutter\.pub-cache\hosted\pub.dartlang.org\media_gallery-0.1.5\android\src\main\kotlin\com\example\media_gallery\MediaGalleryPlugin.kt: (20, 7): Redeclaration: MediaGalleryPlugin
e: C:\flutter\.pub-cache\hosted\pub.dartlang.org\media_gallery-0.1.5\android\src\main\kotlin\com\example\media_gallery\MediaGalleryPlugin.kt: (24, 12): Cannot access 'context': it is private in 'MediaGalleryPlugin'
e: C:\flutter\.pub-cache\hosted\pub.dartlang.org\media_gallery-0.1.5\android\src\main\kotlin\com\example\media_gallery\MediaGalleryPlugin.kt: (43, 14): Cannot access 'context': it is private in 'MediaGalleryPlugin'
e: C:\flutter\.pub-cache\hosted\pub.dartlang.org\media_gallery-0.1.5\android\src\main\kotlin\com\example\media_gallery\MediaGalleryPlugin.kt: (532, 7): Redeclaration: doAsync

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':media_gallery:compileDebugKotlin'.
> Compilation error. See log for more details

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 40s
Exception: Gradle task assembleProductionDebug failed with exit code 1

```
